name: pingit
description: "Cross-platform infrastructure monitoring dashboard with real-time health checks, alerts, and topology visualization."
publish_to: 'none'

version: 1.5.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dart_ping: ^9.0.1
  path_provider: ^2.1.5
  json_annotation: ^4.10.0
  fl_chart: ^1.1.1
  csv: ^6.0.0
  intl: ^0.20.2
  file_picker: ^10.3.10
  flutter_animate: ^4.5.2
  google_fonts: ^8.0.1
  http: ^1.6.0
  mailer: ^6.1.0
  flutter_secure_storage: ^10.0.0
  archive: ^4.0.4
  provider: ^6.1.5+1
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.3
  sqlite3_flutter_libs: ^0.5.21
  path: ^1.9.0
  pdf: ^3.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.12.0
  build_runner: ^2.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
